import {
  MessageSquare,
  Zap,
  Brain,
  PlugZap,
  Clock,
  AlertTriangle,
  Layers,
  LayoutDashboard,
  MessagesSquare,
  Edit3,
  PauseCircle,
  UserCheck,
  BarChart3,
  Download,
  Sliders,
  GitBranch,
  ShieldAlert,
  ShieldCheck,
  FileText,
  BookOpen,
  Wrench,
  FileCheck,
  Rocket,
  HelpCircle,
  Mail,
  LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  MessageSquare,
  Zap,
  Brain,
  PlugZap,
  Clock,
  AlertTriangle,
  Layers,
  LayoutDashboard,
  MessagesSquare,
  Edit3,
  PauseCircle,
  UserCheck,
  BarChart3,
  Download,
  Sliders,
  GitBranch,
  ShieldAlert,
  ShieldCheck,
  FileText,
  BookOpen,
  Wrench,
  FileCheck,
  Rocket,
  HelpCircle,
  Mail,
};

export function getIcon(iconName: string): LucideIcon {
  return iconMap[iconName] || MessageSquare; // fallback to MessageSquare
}
