import db from "@/database/db";
import H1 from "@/components/adminui/h1";
import WhatsAppSim from "@/components/whatsAppSim";
import { getExampleBySlug } from "@/lib/getExamples";
import Image from "next/image";
import Container from "@/components/websiteui/container";
import H2 from "@/components/websiteui/h2";
import Link from "next/link";
import { ChevronLeftIcon } from "@heroicons/react/24/outline";

export default async function ExamplesPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;

  const example = await getExampleBySlug(slug);

  return (
    <div>
      <style>
        {`
          #example-body h2 {
            font-size: 1.2rem;
            font-weight: 600;
            margin-top: 30px;
            margin-bottom: 10px;
          }

          #example-body h3 {
            font-size: 1rem;
            font-weight: 600;
          }

          #example-body p {
            margin-bottom: 30px;
          }

          #example-body ul {
            list-style-type: disc;
            margin-left: 40px;
            margin-bottom: 30px;
          }

          #example-body ol {
            list-style-type: decimal;
            margin-left: 40px;
            margin-bottom: 30px;
          }
        `}
      </style>

      <div className="relative w-full h-[300px]">
        <Image
          src={`/examples/${example.id}.png`}
          alt={example?.title || ""}
          fill
          style={{ objectFit: "cover" }}
          className="w-full h-full"
        />
      </div>

      <Container colour="green">
        <Link href="/examples">
          <div className="flex items-center gap-2 hover:underline">
            <ChevronLeftIcon className="w-6 h-6" /> Back to Examples
          </div>
        </Link>
      </Container>

      <Container>
        <H1>{example.title}</H1>
        <div
          id="example-body"
          dangerouslySetInnerHTML={{ __html: example.body }}
        />
      </Container>

      <Container colour="green">
        <H2>Example Conversations</H2>
        <p>
          Below are some example conversations between a user and the chatbot,
          whilst fictional, they have been generated by the same AI that powers
          the chatbot and represent realistic interactions.
        </p>
      </Container>

      {example.exampleConversations.map((conversation, i) => {
        //change colour for every other one
        const colour = i % 2 === 0 ? "white" : "green";
        return (
          <Container key={i} colour={colour}>
            <div className="flex flex-col gap-8 items-center justify-center">
              <H2 className="text-center">
                {i + 1}. {conversation.description}
              </H2>
              <WhatsAppSim
                messages={conversation.messages}
                businessName={example.businessName}
                startTime={conversation.startTime}
              />
            </div>
          </Container>
        );
      })}
    </div>
  );
}
