import H1 from "@/components/adminui/H1";
import WhatsAppSim from "@/components/whatsAppSim";
import { getExampleBySlug } from "@/lib/getExamples";
import Image from "next/image";
import Container from "@/components/websiteui/container";
import H2 from "@/components/websiteui/h2";
import Link from "next/link";
import { ChevronLeftIcon } from "@heroicons/react/24/outline";
import { MarkdownContent } from "@/components/MarkdownContent";

export default async function ExamplesPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;

  const example = await getExampleBySlug(slug);

  return (
    <div>
      <div className="relative w-full h-[300px]">
        <Image
          src={`https://${process.env.NEXT_PUBLIC_WASABI_ENDPOINT}/voxd/exampleImages/${example.id}.png`}
          alt={example?.title || ""}
          fill
          style={{ objectFit: "cover" }}
          className="w-full h-full"
        />
      </div>

      <Container colour="green">
        <Link href="/examples">
          <div className="flex items-center gap-2 hover:underline">
            <ChevronLeftIcon className="w-6 h-6" /> Back to Examples
          </div>
        </Link>
      </Container>

      <Container>
        <div className="flex flex-col gap-4 items-center justify-center">
          {example.logoFileExtension && (
            <Image
              src={`https://${process.env.NEXT_PUBLIC_WASABI_ENDPOINT}/voxd/exampleLogos/${example.id}.${example.logoFileExtension}`}
              alt={`${example?.businessName} Logo` || ""}
              width={250}
              height={250}
              className="object-contain mb-4"
            />
          )}

          <H1 className="text-center">{example.title}</H1>
          <div className="max-w-3xl w-full">
            <MarkdownContent content={example.body} />
          </div>
        </div>
      </Container>

      <Container colour="green">
        <H2>Example Conversations</H2>
        <p>
          Below are some example conversations between a user and the chatbot,
          whilst fictional, they have been generated by the same AI that powers
          the chatbot and represent realistic interactions.
        </p>
      </Container>

      {example.exampleConversations.map((conversation, i) => {
        //change colour for every other one
        const colour = i % 2 === 0 ? "white" : "green";
        return (
          <Container key={i} colour={colour}>
            <div className="flex flex-col gap-8 items-center justify-center">
              <H2 className="text-center">
                {i + 1}. {conversation.description}
              </H2>
              <WhatsAppSim
                messages={conversation.messages}
                businessName={example.businessName}
                startTime={conversation.startTime}
                exampleId={example.id}
              />
            </div>
          </Container>
        );
      })}
    </div>
  );
}
